#!/usr/bin/python3
import sys

def smallestPrimeFactor(num):
    if num % 2 == 0:
        return 2
    elif num % 3 == 0:
        return 3
    elif num % 5 == 0:
        return 5
    elif num % 7 == 0:
        return 7
    divisor = 3
    while divisor * divisor <= num:
        if num % divisor == 0:
            return divisor
        divisor += 2

    return num


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    file_path = sys.argv[1]
    with open(file_path, 'r') as file:
        for line in file:
            n = int(line)
            factors = smallestPrimeFactor(n)
            print(f"{n}={n // factors}*{factors}")
